<h1><center>Machine Learning</center></h1>
<h1><center>Prediccion con perceptron</center></h1>
<h2><center>Adalberto Emmanuel Rojas Perea 173374</center></h2>
<h2><center>Asesor: Mtra Olanda Prieto</center></h2>

## Exploracion del DataSet
<center><img src="head.jpg"/></center>

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from joblib import dump
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from pandas.plotting import scatter_matrix
from sklearn import datasets
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.impute import SimpleImputer
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix,precision_score, recall_score, f1_score, accuracy_score, classification_report, make_scorer

In [2]:
iris = datasets.load_iris()
list(iris.keys())


['data',
 'target',
 'frame',
 'target_names',
 'DESCR',
 'feature_names',
 'filename',
 'data_module']

### Identificar Features

In [3]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


#### Tenemos 4 features en el dataset: sepal length (cm), sepal width (cm), petal length (cm), petal width (cm)
Aqui una muestra de cuales son cada uno de ellos:
<center><img src="features.png"/></center>

### Target Names

In [4]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


Ahora sabemos el nombre de los target los cuales son : Setosa, Versicolor y Virginica, las cuales mas adelante vamos a tratar de predecir
<center><img src="target_names.png"/></center>

In [5]:
iris["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
df=pd.DataFrame(iris["data"],columns=iris["feature_names"])
df["target"]=iris["target"]
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

2. Realiza una partición de datos para Train y Test con su respectiva etiqueta. (Recuerda que tu partición debe ser reproducible, es decir si ejecutas "n" veces esta instrucción debe arrojar las mismas particiones).

In [7]:
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=0)

In [8]:
print(len(X_train),"train +", len(X_test), "test")

105 train + 45 test


3. Crea un pipeline que realice la transformación de los datos (como standard scale)

In [9]:
feature_tr = Pipeline([("std_scaler", StandardScaler()),])
X_train_tr = feature_tr.fit_transform(X_train) 
X_test_tr = feature_tr.fit_transform(X_test)

4. Guarda la transformación de los datos (pipeline) en un archivo .sav


In [10]:
dump(feature_tr,'pipeline_perceptron.sav')

['pipeline_perceptron.sav']

5. Realizar tus predicciones con los datos de Test. Si tus modelos fueron entrenados con datos transformados (eje. standard scale), será necesario que tu conjunto de datos de test sea transformado

Entrenar el modelo

In [11]:
perceptron_model=Perceptron()
perceptron_model.fit(X_train_tr, y_train)

Perceptron()

Hacer la prediccion

In [12]:
y_pred = perceptron_model.predict(X_test_tr)

Accuracy del modelo

In [13]:
accuracy_perceptron = accuracy_score(y_test, y_pred)
print(f"El accuracy del modelo preceptron es :{accuracy_perceptron: .2f}")

El accuracy del modelo preceptron es : 0.93


Precision del modelo

In [14]:
prec_perceptron = precision_score(y_test, y_pred, average='weighted')
print(f"La precision del modelo perceptron es: {prec_perceptron:.2f}")

La precision del modelo perceptron es: 0.95


Recall

In [15]:
recall_perceptron = recall_score(y_test, y_pred, average='weighted')
print(f"Recall del modelo perceptron: {recall_perceptron:.2f}")

Recall del modelo perceptron: 0.93


F1 score

In [16]:
f1_perc = f1_score(y_test, y_pred, average='weighted')
print(f"F1-score modelo perceptron: {f1_perc:.2f}")

F1-score modelo perceptron: 0.93


Matriz de confusion

In [17]:
matriz_perc = confusion_matrix(y_test, y_pred)
print(matriz_perc)

[[16  0  0]
 [ 0 15  3]
 [ 0  0 11]]


Reporte de clasificacion

In [18]:
reporte_perc = classification_report(y_test, y_pred)
print(reporte_perc)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.83      0.91        18
           2       0.79      1.00      0.88        11

    accuracy                           0.93        45
   macro avg       0.93      0.94      0.93        45
weighted avg       0.95      0.93      0.93        45



7. Almacena tus modelos entrenados en un archivo .sav.

In [19]:
dump(perceptron_model, 'model_perceptron.sav')

['model_perceptron.sav']